name: Add solutions

on:
  # Run workflow on pushes to main branch
  issues:
    types: [closed]
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.labels[1].name == 'accepted' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: |-
          git config --global user.email "saurabh.singh2019@vitstudent.ac.in"
          git config --global user.name "baazis"
          git pull
          python3 script.py '${{ github.event.issue.body }}'   
          
      - name: Commit and push if changed
        run: |-
          git diff
          git add .
          git commit -m "Merge solution"
          git push
